# Generated by Django 3.2.4 on 2021-06-28 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mo', models.FloatField(blank=True, null=True)),
                ('valor_materiales', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.clientes')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, unique=True, verbose_name='Cargo')),
                ('salario', models.FloatField(verbose_name='Salario')),
            ],
            options={
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=120, verbose_name='Marca')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('unidad', models.CharField(choices=[('PZA', 'PIEZA'), ('UND', 'UNIDAD'), ('M', 'METRO LINEAR'), ('KG', 'KILOGRAMO')], default='PZA', max_length=3, verbose_name='Unidad')),
            ],
            options={
                'ordering': ['material_nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreciosUnitarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mo', models.FloatField(blank=True, null=True)),
                ('valor_material', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('unidades_jornal', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidad', models.FloatField(default=0.15)),
                ('iva', models.FloatField(default=1.1494)),
                ('gastos_admin', models.FloatField(default=0.1)),
                ('herramientas', models.FloatField(default=0.02)),
                ('seguridad', models.FloatField(default=0.04)),
            ],
        ),
        migrations.CreateModel(
            name='PuMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_id', to='cotizacion.materiales')),
                ('puma_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puma_id', to='cotizacion.preciosunitarios')),
            ],
            options={
                'unique_together': {('material_id', 'puma_id')},
            },
        ),
        migrations.CreateModel(
            name='PuManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_jornal', models.FloatField(blank=True, null=True)),
                ('mo_subtotal', models.FloatField(blank=True, null=True)),
                ('ctd', models.PositiveIntegerField(default=1)),
                ('manoobra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manoobra_id', to='cotizacion.manoobra')),
                ('pumo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pumo_id', to='cotizacion.preciosunitarios')),
            ],
        ),
        migrations.AddField(
            model_name='preciosunitarios',
            name='mano_obra',
            field=models.ManyToManyField(related_name='mano_obra', through='cotizacion.PuManoObra', to='cotizacion.ManoObra'),
        ),
        migrations.AddField(
            model_name='preciosunitarios',
            name='material_id',
            field=models.ManyToManyField(related_name='material', through='cotizacion.PuMaterial', to='cotizacion.Materiales'),
        ),
        migrations.AddField(
            model_name='preciosunitarios',
            name='rendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimiento', to='cotizacion.rendimientos'),
        ),
        migrations.CreateModel(
            name='ItemCotiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('valor_material', models.FloatField(blank=True, null=True)),
                ('valor_mo', models.FloatField(blank=True, null=True)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizacion.cotizaciones')),
                ('pu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.preciosunitarios')),
            ],
            options={
                'unique_together': {('cotizacion_id', 'pu_id')},
            },
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='pu_id',
            field=models.ManyToManyField(through='cotizacion.ItemCotiza', to='cotizacion.PreciosUnitarios'),
        ),
    ]
